Fix a bunch of issues
GTNewHorizons/Backhand pull request #10
Opened 2024-07-24 17:29 UTC by Lyfts

The mysterium transformer wasn't being initiated which meant that its [weird patches](https://github.com/GTNewHorizons/Backhand/blob/master/src/main/java/net/tclproject/mysteriumlib/asm/fixes/MysteriumPatchesFixesO.java) (wow this could use a mixin conversion) were never applied. Instead of having 2 coremods I merged the mysterium fix loader doohickey into the Backhand coremod and added the two missing transformers.
This fixed the majority of the problems and
Fixes https://github.com/GTNewHorizons/Backhand/issues/4, fixes https://github.com/GTNewHorizons/Backhand/issues/8, fixes https://github.com/GTNewHorizons/Backhand/issues/5

I also fixed some incorrect interactions with EFR's totem of undying, tipped arrows & fireworks which
Fixes https://github.com/GTNewHorizons/Backhand/issues/9, https://github.com/GTNewHorizons/Backhand/issues/6, https://github.com/GTNewHorizons/Backhand/issues/7

I also ditched the access transformer class because it was both pointing to the wrong file and not necessary

2024-07-24 18:16 UTC, Caedis requested changes

2024-07-24 18:16 UTC, Caedis commented on src/main/java/xonin/backhand/ServerEventsHandler.java
> +        }
Needs a mod guard for EFR

2024-07-24 18:52 UTC, Lyfts commented on src/main/java/xonin/backhand/ServerEventsHandler.java
> +        }
idfk how I forgot that

2024-07-24 19:02 UTC, Caedis approved these changes

2024-07-25 01:13 UTC, merged

2024-07-25 08:32 UTC, huihiuhuai commented
Have you considered forking the 1.4.1 version?

2024-07-25 08:45 UTC, Lyfts commented
No

2024-07-25 10:06 UTC, Caedis commented
We are actually based on the 1.4.1 version if you check the commit history

2024-07-25 10:17 UTC, huihiuhuai commented
> We are actually based on the 1.4.1 version if you check the commit history

but 1.4.1 doesn't have most of the aforementioned issues..